### ISSUE TITLE
TS-Node not working properly

### ISSUE THREAD

**Issue by Shurtu-gal** [oclif/core#1273]
**Describe the bug**
I am trying to create a `dev` script which doesn't require build each time.

**Expected behavior**
Should work by transpiling my code.

**Debug Log**
```
oclif:main process.execPath: /usr/bin/node +0ms
  oclif:main process.execArgv: /home/shurtu-gal/.npm-packages/lib/node_modules/ts-node/dist/bin.js +1ms
  oclif:main process.argv: [
  oclif:main   '/home/shurtu-gal/.npm-packages/bin/ts-node',
  oclif:main   '/home/shurtu-gal/work/asyncapi/cli/bin/dev',
  oclif:main   'generate',
  oclif:main   'models'
  oclif:main ] +0ms
  oclif:find-root:root-plugin Finding root plugin using /home/shurtu-gal/work/asyncapi/cli/bin +0ms
  oclif:find-root:root-plugin Finding root starting at /home/shurtu-gal/work/asyncapi/cli/bin +0ms
  oclif:find-root:root-plugin Checking /home/shurtu-gal/work/asyncapi/cli/bin/package.json +0ms
  oclif:find-root:root-plugin Checking /home/shurtu-gal/work/asyncapi/cli/package.json +1ms
  oclif:find-root:root-plugin Found root by traversing up from starting point! +0ms
  oclif:find-root:root-plugin Found root at /home/shurtu-gal/work/asyncapi/cli +0ms
  oclif:config loading core plugin from /home/shurtu-gal/work/asyncapi/cli +0ms
  oclif:read-pjson found oclif config in /home/shurtu-gal/work/asyncapi/cli/package.json +0ms
  oclif:config:@asyncapi/cli command discovery options {
  globPatterns: [
    '**/*.+(js|cjs|mjs|ts|tsx|mts|cts)',
    '!**/*.+(d.ts|test.ts|test.js|spec.ts|spec.js|d.mts|d.cts)?(x)'
  ],
  strategy: 'pattern',
  target: './lib/commands'
} +0ms
  oclif:config:@asyncapi/cli using manifest from /home/shurtu-gal/work/asyncapi/cli/oclif.manifest.json +2ms
  oclif:config reading user plugins pjson /home/shurtu-gal/.local/share/@asyncapi/cli/package.json +13ms
  oclif:config config done +4ms
  oclif:config start init hook +1ms
  oclif:config init hook done +0ms
  oclif:config runCommand generate:models [] +0ms
  oclif:config:ts-path tsconfig: {
  oclif:config:ts-path   compilerOptions: {
  oclif:config:ts-path     isolatedModules: true,
  oclif:config:ts-path     resolveJsonModule: true,
  oclif:config:ts-path     moduleResolution: 'node',
  oclif:config:ts-path     noFallthroughCasesInSwitch: true,
  oclif:config:ts-path     forceConsistentCasingInFileNames: true,
  oclif:config:ts-path     strict: true,
  oclif:config:ts-path     allowSyntheticDefaultImports: true,
  oclif:config:ts-path     esModuleInterop: true,
  oclif:config:ts-path     skipLibCheck: true,
  oclif:config:ts-path     allowJs: true,
  oclif:config:ts-path     importHelpers: true,
  oclif:config:ts-path     declaration: true,
  oclif:config:ts-path     lib: [ 'esnext' ],
  oclif:config:ts-path     module: 'commonjs',
  oclif:config:ts-path     target: 'es6',
  oclif:config:ts-path     baseUrl: './src',
  oclif:config:ts-path     outDir: './lib'
  oclif:config:ts-path   },
  oclif:config:ts-path   'ts-node': {}
  oclif:config:ts-path } +0ms
  oclif:config:ts-path Determining path for /home/shurtu-gal/work/asyncapi/cli/lib/commands +1ms
  oclif:config:ts-path Could not find tsx. Skipping tsx registration for /home/shurtu-gal/work/asyncapi/cli. +0ms
  oclif:config:ts-path Error: Cannot find module 'tsx/cjs/api'
  oclif:config:ts-path Require stack:
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/ts-path.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/help/index.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/errors/handle.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/errors/index.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/config.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/index.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/command.js
  oclif:config:ts-path - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/index.js
  oclif:config:ts-path     at Function.<anonymous> (node:internal/modules/cjs/loader:1241:15)
  oclif:config:ts-path     at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/shurtu-gal/.npm-packages/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
  oclif:config:ts-path     at Function.resolve (node:internal/modules/helpers:146:19)
  oclif:config:ts-path     at registerTsx (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/ts-path.js:88:33)
  oclif:config:ts-path     at determinePath (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/ts-path.js:207:15)
  oclif:config:ts-path     at async tsPath (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/ts-path.js:285:16)
  oclif:config:ts-path     at async Plugin.getCommandsDir (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:347:28)
  oclif:config:ts-path     at async fetch (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:122:37)
  oclif:config:ts-path     at async Plugin.findCommand (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:159:21)
  oclif:config:ts-path     at async Config.runCommand (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/config.js:422:25) +0ms
  oclif:config:ts-path registering ts-node at /home/shurtu-gal/work/asyncapi/cli +2ms
  oclif:config:ts-path ts-node path: /home/shurtu-gal/work/asyncapi/cli/node_modules/ts-node/dist/index.js +0ms
  oclif:config:ts-path Successfully required ts-node +9ms
  oclif:config:ts-path ts-node options: {
  oclif:config:ts-path   compilerOptions: {
  oclif:config:ts-path     isolatedModules: true,
  oclif:config:ts-path     resolveJsonModule: true,
  oclif:config:ts-path     moduleResolution: 'node',
  oclif:config:ts-path     noFallthroughCasesInSwitch: true,
  oclif:config:ts-path     forceConsistentCasingInFileNames: true,
  oclif:config:ts-path     strict: true,
  oclif:config:ts-path     allowSyntheticDefaultImports: true,
  oclif:config:ts-path     esModuleInterop: true,
  oclif:config:ts-path     skipLibCheck: true,
  oclif:config:ts-path     allowJs: true,
  oclif:config:ts-path     importHelpers: true,
  oclif:config:ts-path     declaration: true,
  oclif:config:ts-path     lib: [ 'esnext' ],
  oclif:config:ts-path     module: 'commonjs',
  oclif:config:ts-path     target: 'es6',
  oclif:config:ts-path     outDir: './lib',
  oclif:config:ts-path     rootDirs: [ '/home/shurtu-gal/work/asyncapi/cli/src' ],
  oclif:config:ts-path     typeRoots: [ '/home/shurtu-gal/work/asyncapi/cli/node_modules/@types' ]
  oclif:config:ts-path   },
  oclif:config:ts-path   cwd: '/home/shurtu-gal/work/asyncapi/cli',
  oclif:config:ts-path   esm: true,
  oclif:config:ts-path   experimentalSpecifierResolution: 'explicit',
  oclif:config:ts-path   scope: true,
  oclif:config:ts-path   scopeDir: '/home/shurtu-gal/work/asyncapi/cli',
  oclif:config:ts-path   skipProject: true,
  oclif:config:ts-path   transpileOnly: true
  oclif:config:ts-path } +0ms
  oclif:config:ts-path lib dir: /home/shurtu-gal/work/asyncapi/cli/lib +7ms
  oclif:config:ts-path src dir: /home/shurtu-gal/work/asyncapi/cli/src +0ms
  oclif:config:ts-path src directory to find: /home/shurtu-gal/work/asyncapi/cli/src/commands +0ms
  oclif:config:ts-path Found source directory for /home/shurtu-gal/work/asyncapi/cli/lib/commands at /home/shurtu-gal/work/asyncapi/cli/src/commands +0ms
ModuleLoadError: [MODULE_NOT_FOUND] require failed to load /home/shurtu-gal/work/asyncapi/cli/lib/commands/generate/models.js: Cannot find module '/home/shurtu-gal/work/asyncapi/cli/lib/commands/generate/models.js'
Require stack:
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/module-loader.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/help/index.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/errors/handle.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/errors/index.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/config.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/index.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/command.js
- /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/index.js
    at handleError (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/module-loader.js:21:15)
    at loadWithDataFromManifest (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/module-loader.js:112:9)
    at fetch (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:131:78)
    at async Plugin.findCommand (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:159:21)
    at async Config.runCommand (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/config.js:422:25)
    at async run (/home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/main.js:95:16)
    at async /home/shurtu-gal/work/asyncapi/cli/bin/dev:6:3
  oclif:error ModuleLoadError: [MODULE_NOT_FOUND] require failed to load /home/shurtu-gal/work/asyncapi/cli/lib/commands/generate/models.js: Cannot find module '/home/shurtu-gal/work/asyncapi/cli/lib/commands/generate/models.js'
  oclif:error Require stack:
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/module-loader.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/help/index.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/errors/handle.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/errors/index.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/config.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/config/index.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/command.js
  oclif:error - /home/shurtu-gal/work/asyncapi/cli/node_modules/@oclif/core/lib/index.js
  oclif:error     at handleError (~/work/asyncapi/cli/node_modules/@oclif/core/lib/module-loader.js:21:15)
  oclif:error     at loadWithDataFromManifest (~/work/asyncapi/cli/node_modules/@oclif/core/lib/module-loader.js:112:9)
  oclif:error     at fetch (~/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:131:78)
  oclif:error     at async Plugin.findCommand (~/work/asyncapi/cli/node_modules/@oclif/core/lib/config/plugin.js:159:21)
  oclif:error     at async Config.runCommand (~/work/asyncapi/cli/node_modules/@oclif/core/lib/config/config.js:422:25)
  oclif:error     at async run (~/work/asyncapi/cli/node_modules/@oclif/core/lib/main.js:95:16)
  oclif:error     at async ~/work/asyncapi/cli/bin/dev:6:3 +0ms
```

**Environment (please complete the following information):**
 - OS & version: Arch Linux
 - Shell/terminal & version: Fish-3.7.1

**Comment by mdonnalley** [comment]
Can you share a repo that replicates the issue? Thanks

**Comment by Shurtu-gal** [comment]
Yeah, I made another branch here: https://github.com/Shurtu-gal/cli/tree/replicate

**Comment by mdonnalley** [comment]
@Shurtu-gal This log line indicates that you have a local `oclif.manifest.json`:

```
oclif:config:@asyncapi/cli using manifest from /home/shurtu-gal/work/asyncapi/cli/oclif.manifest.json
```

The manifest is going to tell oclif where to find the file for the command you're executing. In this case, `/home/shurtu-gal/work/asyncapi/cli/lib/commands/generate/models.js`. But if that file doesn't exist, you're going to get the `MODULE_NOT_FOUND` error.

To fix, you should delete the `oclif.manifest.json` - which shouldn't exist when you're developing anyways

**Comment by Shurtu-gal** [comment]
Oh that makes sense. Thank you so  much 💓.
