### ISSUE TITLE
"AbortController is not defined" error on Node 14

### ISSUE THREAD

**Issue by vlukashov** [oclif/core#630]
**Describe the bug**
Running any CLI based on `@oclif/core` 2+ on Node 14 consistenly fails with "ReferenceError: AbortController is not defined" in some cases.

**To Reproduce**
1. create a new oclif CLI with `npx oclif generate my-oclif-core2-cli`
2. install the latest Node 14 with `nvm install 14 && nvm use 14`
3. run the `hello` command when the terminal is not interactive: `head -n1 package.json | bin/dev hello -f NodeJS`
4. See the error
```
ReferenceError: AbortController is not defined
    at /path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/parser/parse.js:28:20
    at new Promise (<anonymous>)
    at readStdin (/path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/parser/parse.js:26:12)
    at Parser._args (/path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/parser/parse.js:275:35)
    at Parser.parse (/path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/parser/parse.js:161:43)
    at Object.parse (/path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/parser/index.js:18:33)
    at Hello.parse (/path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/command.js:193:38)
    at Hello.run (/path/to/my-oclif-core2-cli/src/commands/hello/index.ts:28:40)
    at Hello._run (/path/to/my-oclif-core2-cli/node_modules/@oclif/core/lib/command.js:107:33)
```

**Expected behavior**
The CLI should produce the same output on Node 14 as it does on Node 16 or newer:
```
$ head -n1 package.json | bin/dev hello -f NodeJS
hello { from NodeJS! (./src/commands/hello/index.ts)
```

**Screenshots**
<img width="963" alt="image" src="https://user-images.githubusercontent.com/22416150/218792967-1c1a40b9-46c5-4040-8e92-84b4b9b4630f.png">

**Environment (please complete the following information):**
 - MacOS Monterey
 - zsh 5.8.1

**Additional context**
The root cause seems to be in using the [`AbortController`](https://github.com/oclif/core/blob/f78ae24975cb11ea320dd911ea7ab48df2c76d19/src/parser/parse.ts#L27) API assuming that it's always available. However, this API was added in Node 15 and is not available in Node 12 and 14. Since oclif [claims](https://github.com/oclif/oclif#-requirements) to support Node 12+ it should either load an AbortController API polyfill or stop using this API.

**Comment by shazron** [comment]
It looks like version 2.9.x of @oclif/core does not support node-14 anymore, without making it a major version bump. https://github.com/oclif/core/discussions/737

@mshanemc @jdxcode
